name: 'Terraform Destroy'

on:
  workflow_dispatch: # Cho phép nhấn nút chạy thủ công trên giao diện GitHub
    inputs:
      environment:
        description: 'Environment to destroy (dev, prod, or main)'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - prod
          - main

permissions:
  contents: read
  id-token: write

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v3

      - name: Determine Environment Path
        id: environment
        run: |
          if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
            echo "env_path=environments/dev" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            echo "env_path=environments/prod" >> $GITHUB_OUTPUT
          else
            echo "env_path=." >> $GITHUB_OUTPUT
          fi

      - name: Terraform Init
        run: |
          cd ${{ steps.environment.outputs.env_path }}
          terraform init

      - name: Terraform Destroy
        run: |
          cd ${{ steps.environment.outputs.env_path }}
          terraform destroy -auto-approve
